#!/usr/bin/env zsh

function update_git_completions {
  emulate -L zsh
  local giturl=https://raw.githubusercontent.com/git/git/master/contrib/completion
  local dest=${1:-${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/completions}
  [[ -d $dest ]] || mkdir -p $dest
  echo "Updating git completions in $dest ..."
  curl -fsSL $giturl/git-completion.bash -o $dest/git-completion.bash \
    && curl -fsSL $giturl/git-completion.zsh -o $dest/_git \
    && echo "Done. Restart your shell or run 'compinit' to pick up changes." \
    || echo "Failed to download git completions."
}
update_git_completions "$@"
